# Generated by Django 2.1.1 on 2019-01-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('report_json', models.TextField()),
                ('report_hash', models.CharField(max_length=2000)),
                ('plan_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanYear')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.Village')),
            ],
        ),
    ]
